df4j:
  xcframework:
    datasource:
      enabled: false
      default-key: xcms
      datasources:
        xcms:
          type: hikari
          master: master
          nodes:
            master:
              url: jdbc:mysql://ywz:3306/xcms
              username: wangxc
              passowrd: wxc@199008
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://ywz:3306/xcms
    username: wangxc
    password: wxc@199008
  cache:
    type: caffeine
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
  redis:
    host: ywz
    port: 6379
    password: 123456
    database: 0
debug: false
logging:
  config: ""
  level:
    root: info