spring:
  application:
    name: df4j-xcms
  profiles:
    include: xcframework
    active: dev
  data:
    jpa:
      repositories:
        bootstrap-mode: default
        enabled: true
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
  datasource:
    hikari:
      validation-timeout: 10000
server:
  port: 8080
mybatis:
  check-config-location: true
  type-aliases-package: com.df4j.xcms.*.model
  mapper-locations:
    - classpath:com/df4j/xcms/xmlmapper/*.xml