df4j:
  xcframework:
    datasource:
      enabled: false
      default-key: xcms
      datasources:
        xcms:
          type: hikari
          master: master
          nodes:
            master:
              url: jdbc:mysql://localhost:3306/xcms
              username: xcms
              passowrd: xcms1234
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/xcms
    username: xcms
    password: xcms1234
  cache:
    type: caffeine
    cache-names: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
debug: false
logging:
  config: ""
  level:
    root: info