###
POST {{localXcmsServer}}/api/xcms/core/user/login
Content-Type: application/json

{
  "userName": "xcms",
  "userPass": "xcms1234"
}

###
POST {{localXcmsServer}}/api/xcms/core/user/info
Content-Type: application/json

{}
